### ISSUE TITLE
Benefits of running Orleans on Service Fabric

### ISSUE THREAD

**Issue by pisees** [ReubenBond/OrleansFabricSilo#1]
Hi, 
This is quite interesting. What are the key benefits you see to this approach?

**Comment by ReubenBond** [comment]
Service Fabric gives us the ability to upgrade the application much more quickly than Azure Cloud Services. It also lets me pack many services into a given machine, so I can cram lots of little Web services on a small set of nodes (call them microservices if you wish...).

**Comment by pisees** [comment]
Great, thanks for the feedback
